Traceback (most recent call last):
  File "/Users/quannguyen/opt/miniconda3/envs/mds574/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/quannguyen/opt/miniconda3/envs/mds574/lib/python3.7/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/quannguyen/opt/miniconda3/envs/mds574/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/quannguyen/opt/miniconda3/envs/mds574/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/quannguyen/opt/miniconda3/envs/mds574/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/quannguyen/opt/miniconda3/envs/mds574/lib/python3.7/site-packages/nbclient/client.py", line 552, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/quannguyen/opt/miniconda3/envs/mds574/lib/python3.7/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/quannguyen/opt/miniconda3/envs/mds574/lib/python3.7/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
MATH => CHEM support
------------------

Error in parse(text = x, srcfile = src): '=>' is disabled; set '_R_USE_PIPEBIND_' envvar to a true value to enable it
Traceback:

ERROR: Error in parse(text = x, srcfile = src): '=>' is disabled; set '_R_USE_PIPEBIND_' envvar to a true value to enable it


